dataset: "LibriTTS"

path:
  df_path: "/home/heiscold/preprocessed/german_one_speaker_2037_rs_22k_seq1500/german_one_speaker_2037_13k_triagnle.csv"
  corpus_path: "/home/ming/Data/LibriTTS/train-clean-360" 
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "./raw_data/LibriTTS" # in_dir
  preprocessed_path: "/home/heiscold/preprocessed/german_one_speaker_2037_rs_22k_seq1k" # "./preprocessed_data/LibriTTS" # out

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["transliteration_cleaners"] # ["english_cleaners"] # ["transliteration_cleaners"]
    language: "german"
  audio:
    load_audio_library : 'torchaudio' # support 'torchaudio'
    denoiser: False 
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
