path:

  ## t4mr_17
  ## /home/heiscold/preprocessed/german_one_speaker_rs_22k_seq_1k/train_ger_13100_one_speaker_10148.csv
  ## based on the preprocessed data of t4mr_10 //
  ckpt_path: '/home/heiscold/outcome_german/t4mr_17/ckpt' # "./output/ckpt/LibriTTS"
  log_path: '/home/heiscold/outcome_german/t4mr_17/log' # "./output/log/LibriTTS"
  result_path: '/home/heiscold/outcome_german/t4mr_17/result' # "./output/result/LibriTTS"

optimizer:
  batch_size: 48
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 100
  synth_step: 10000
  val_step: 1000
  save_step: 100000
